swagger: "2.0"
info:
  title: beego Test API
  description: |
    beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths: {}
definitions:
  models.Object:
    title: Object
    type: object
    properties:
      ObjectId:
        type: string
      PlayerName:
        type: string
      Score:
        type: integer
        format: int64
  models.Task:
    title: Task
    type: object
    properties:
      Description:
        type: string
      EndDate:
        type: string
        format: datetime
      Id:
        type: integer
        format: int64
      Location:
        type: string
      StartDate:
        type: string
        format: datetime
      Task_code:
        type: string
      Title:
        type: string
  models.User:
    title: User
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Password:
        type: string
      Task:
        $ref: '#/definitions/models.Task'
      UserCode:
        type: string
      Username:
        type: string
